--[[
--TRIKYTA ENGINE:
	Check HowToLuaTrikyta.lua for documentation
--Special thanks to:
--Thomas Decroix (Tricky Patrick aka.ThoThoBoss)
--]]

WINDOW_WIDTH				= 1024*1.6				--WINDOW WIDTH
WINDOW_HEIGHT				= 768*1.2				--WINDOW HEIGHT
WINDOW_NAME					= "Trikyta Engine"		--WINDOW NAME
ACCELERATION_RATE			= 1						--THE LOWER THE FASTER
PHYSICS_DEBUG				= true					--SHOW PHYSICS BODIES
PHYSICS_TIME_STEP			= 1/60					--PHYSICS UPDATE RATE
PHYSICS_VELOCITY_ITERATIONS = 8						--PHYSICS VELCOTIY ITERATIONS
PHYSICS_POSITION_ITERATIONS = 3						--PHYSICS POSITION ITERATIONS
PHYSICS_WORLD_GRAVITY_X		= 0						--PHYSICS WORLD GRAVITY X
PHYSICS_WORLD_GRAVITY_Y		= 10					--PHYSICS WORLD GRAVITY Y